[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000280DBE945A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/1c57db77febffdaaf23cd94cca4d8a3a
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000280DBE94D10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/1c57db77febffdaaf23cd94cca4d8a3a
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000280DBE94F30>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/1c57db77febffdaaf23cd94cca4d8a3a