{"name": "test_invalid_otp_entry", "status": "passed", "description": "Verify error message for incorrect OTP entry.", "start": 1742288058469, "stop": 1742288079147, "uuid": "7bed62e7-184b-4bfe-b93f-438dc00bad6e", "historyId": "fa4409ee4aab868165e0af47b2ca0b90", "testCaseId": "fa4409ee4aab868165e0af47b2ca0b90", "fullName": "tests.test_03_forgot_password.TestForgotPassword#test_invalid_otp_entry", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('driver')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_03_forgot_password"}, {"name": "subSuite", "value": "TestForgotPassword"}, {"name": "host", "value": "DESKTOP-LHJT9BM"}, {"name": "thread", "value": "19928-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_03_forgot_password"}]}